apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ray-service.vllm.yaml

patches:
  - path: add-ray-worker-toleration.yaml
    target:
      kind: RayService
      name: ray-model-garden
  - path: patch-headgroup.yaml
    target:
      kind: RayService
      name: ray-model-garden
