apiVersion: apps/v1
kind: Deployment
metadata:
  name: bedrock-proxy
  labels:
    app: bedrock-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bedrock-proxy
  template:
    metadata:
      labels:
        app: bedrock-proxy
    spec:
      serviceAccountName: bedrock-invoke-sa  # uses IRSA for AWS access
      containers:
        - name: proxy
          image: 891377002699.dkr.ecr.us-east-2.amazonaws.com/clearfracture/bedrock-proxy:latest
          ports:
            - containerPort: 8000
          env:
            - name: AWS_REGION
              value: "us-east-2"
---
apiVersion: v1
kind: Service
metadata:
  name: bedrock-proxy-svc
spec:
  selector:
    app: bedrock-proxy
  ports:
    - port: 8000
      targetPort: 8000
