addonsConfig: {}
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
managedNodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 1
  disableIMDSv1: true
  disablePodIMDS: false
  iam:
    withAddonPolicies:
      albIngress: false
      appMesh: false
      appMeshPreview: false
      autoScaler: false
      awsLoadBalancerController: false
      certManager: false
      cloudWatch: false
      ebs: false
      efs: false
      externalDNS: false
      fsx: false
      imageBuilder: false
      xRay: false
  instanceSelector: {}
  instanceTypes:
  - m5.large
  labels:
    alpha.eksctl.io/cluster-name: clear-fracture-public-cluster
    alpha.eksctl.io/nodegroup-name: ray-head
    role: ray-head
  taints:
    - key: role
      value: ray-head
      effect: NoSchedule
  maxSize: 2
  minSize: 1
  name: ray-head
  privateNetworking: false
  releaseVersion: ""
  securityGroups:
    withLocal: null
    withShared: null
  ssh:
    allow: true
    publicKeyPath: keith-laptop
  tags:
    alpha.eksctl.io/nodegroup-name: ray-head
    alpha.eksctl.io/nodegroup-type: managed
  volumeIOPS: 3000
  volumeSize: 80
  volumeThroughput: 125
  volumeType: gp3
metadata:
  name: clear-fracture-public-cluster
  region: us-east-2
  version: "1.32"
